/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.paingan.yuiui.swing;

import org.paingan.yuiui.service.YUICompressor;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.paingan.yuiui.Options;

/**
 *
 * @author paulusyansen
 */
public class YUIFrame extends javax.swing.JFrame {

    /**
     * Creates new form YUIGUIFrame
     */
    public YUIFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspConsole = new javax.swing.JScrollPane();
        txtConsole = new javax.swing.JTextArea();
        lblSource = new javax.swing.JLabel();
        txtPath = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple YUI Compressor v0.3 beta");
        setName("frm"); // NOI18N
        setResizable(false);

        txtConsole.setEditable(false);
        txtConsole.setColumns(20);
        txtConsole.setRows(5);
        jspConsole.setViewportView(txtConsole);

        lblSource.setText("File Source:");

        txtPath.setEditable(false);
        txtPath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPathMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSource)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPath))
                    .addComponent(jspConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSource)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPathMouseClicked
        JFileChooser jfc = new JFileChooser(new File(System.getProperty("user.dir")));
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("javascript, css, html","js","css","html");
        jfc.setFileFilter(filter);
        jfc.setDialogTitle("Choose a directory or file: ");
        jfc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        jfc.setMultiSelectionEnabled(false);

        int returnValue = jfc.showSaveDialog(null);
        
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            
            if (jfc.getSelectedFile().isFile()) {
                txtPath.setText(jfc.getSelectedFile().getAbsolutePath());
                
                String inputFilename = jfc.getSelectedFile().getAbsolutePath();
                int index = jfc.getSelectedFile().getName().indexOf(".");
                String filename = jfc.getSelectedFile().getName().substring(0, index);
                String ext = jfc.getSelectedFile().getName().substring(index);

                String outputFilename = jfc.getSelectedFile().getParent() +"/"+ filename +".min"+ ext;
                Options o = new Options();

                try {
                    if(".js".equals(ext)) {
                        YUICompressor.compressJavaScript(inputFilename, outputFilename, o);
                        txtConsole.append(jfc.getSelectedFile().getName()+" JS file compress successfully\n");
                    } 
                    if(".css".equals(ext)) {
                        YUICompressor.compressCSS(inputFilename, outputFilename, o);
                        txtConsole.append(jfc.getSelectedFile().getName()+" CSS file compress successfully\n");
                    }
                    if(".html".equals(ext)) {
                        YUICompressor.compressHTML(inputFilename, outputFilename, o);
                        txtConsole.append(jfc.getSelectedFile().getName()+" HTML file compress successfully\n");
                    }

                } catch (Exception ex) {
                    Logger.getLogger(YUIFrame.class.getName()).log(Level.SEVERE, null, ex);

                    txtConsole.append(ex.getMessage()+"\n");
                }
            }
            
            if(jfc.getSelectedFile().isDirectory()) {
                File[] filesInDirectory = jfc.getSelectedFile().listFiles();
                
                for ( File file : filesInDirectory ) {
                    txtPath.setText(jfc.getSelectedFile().getAbsolutePath());
                    
                    String fileNameExt = file.getName();
                    String inputFilename = file.getAbsolutePath();
                    int index = fileNameExt.indexOf(".");
                    
                    if(index > 0) { // must has extension
                        String ext = fileNameExt.substring(index);
                        String filename = fileNameExt.substring(0, index);
                        String outputFilename = file.getParent() +"/"+ filename +".min"+ ext;
                        Options o = new Options();
                        
                        try {
                            if(".js".equals(ext)) {
                                YUICompressor.compressJavaScript(inputFilename, outputFilename, o);
                                txtConsole.append(jfc.getSelectedFile().getName()+" JS file compress successfully\n");
                            } 
                            if(".css".equals(ext)) {
                                YUICompressor.compressCSS(inputFilename, outputFilename, o);
                                txtConsole.append(jfc.getSelectedFile().getName()+" CSS file compress successfully\n");
                            }
                            if(".html".equals(ext)) {
                                YUICompressor.compressHTML(inputFilename, outputFilename, o);
                                txtConsole.append(jfc.getSelectedFile().getName()+" HTML file compress successfully\n");
                            }

                        } catch (Exception ex) {
                            Logger.getLogger(YUIFrame.class.getName()).log(Level.SEVERE, null, ex);
                            txtConsole.append(ex.getMessage()+"\n");
                        }
                    }
                }
            }
        } else {
            txtConsole.setText("No file chosen!");
        }
    }//GEN-LAST:event_txtPathMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YUIFrame().setVisible(true);
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jspConsole;
    private javax.swing.JLabel lblSource;
    private javax.swing.JTextArea txtConsole;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables
}